apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: mettallb-ip-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.6.210-192.168.6.219 # set your ip range
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: my-l2-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - mettallb-ip-pool
