apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx # you have to have a pod with this label
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
  loadBalancerIP: 192.168.6.210  # Assigning a specific IP from MetalLB's range
